name: Deploy to ZAP Hosting

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Upload to ZAP via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.2
        with:
          server: ${{ secrets.ZAP_HOST }}
          username: ${{ secrets.ZAP_USER }}
          password: ${{ secrets.ZAP_PASS }}
          server-dir: /fivem/Qbox_052EBB.base/resources/
          local-dir: ./resources/
          port: 21
          protocol: ftp
