name: Deploy to ZAP Hosting (Stable FTP Only)

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'resources/[EUP]/**'
      - 'resources/**/eup-stream/**'
      - 'resources/**/stream/**'
      - '.ftp-deploy-sync-state.json'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload to ZAP (Stable FTP)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.2
        with:
          server: ${{ secrets.ZAP_HOST }}
          username: ${{ secrets.ZAP_USER }}
          password: ${{ secrets.ZAP_PASS }}

          protocol: ftp
          port: 21

          timeout: 300000   # Prevents disconnects

          local-dir: ./resources/
          server-dir: /g686818/fivem/Qbox_052EBB.base/resources/

          state-name: ftp-sync-state.json
          dangerous-clean-slate: false

          exclude: |
            **/node_modules/**
            **/.github/**
            **/.git/**
            **/LICENSE**
            **/README.md

            resources/[EUP]/**
            resources/[standalone]/**

            resources/EUP/**
            resources/standalone/**

            **/eup-stream/**
            **/stream/**
            **/[[]*[]]**
            .ftp-deploy-sync-state.json
            ftp-sync-state.json
