name: Deploy to ZAP Hosting (Fast)

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'resources/[EUP]/**'
      - 'resources/**/eup-stream/**'
      - 'resources/**/stream/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload to ZAP (FAST)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.2
        with:
          server: ${{ secrets.ZAP_HOST }}
          username: ${{ secrets.ZAP_USER }}
          password: ${{ secrets.ZAP_PASS }}

          server-dir: /g686818/fivem/Qbox_052EBB.base/resources/
          local-dir: ./resources/

          protocol: ftp
          port: 21
          dangerous-clean-slate: false

          exclude: |
            **/node_modules/**
            **/.github/**
            **/.git/**
            **/README.md
            **/LICENSE**

            # Ignore bracketed folders in GitHub repo
            resources/[standalone]/**
            resources/[EUP]/**

            # Ignore actual folders on ZAP Hosting (brackets removed)
            resources/standalone/**
            resources/EUP/**

            # Ignore EUP subfolders
            resources/**/eup-stream/**
            resources/**/stream/**

            # Ignore ANY folder that contains brackets (generic rule)
            **/[[]*[]]**
